name: mobicar_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.2
  mobx: ^2.0.5
  dartz: ^0.10.1
  google_fonts: ^2.1.0
  hive: ^2.0.4
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - lib/app/designsystem/assets/images/logo.svg
    - lib/app/designsystem/assets/images/icon_drawer.svg
    - lib/app/designsystem/assets/images/drawer_background.png
    - lib/app/designsystem/assets/images/icon.png

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/app/designsystem/assets/images/icon.png"

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
